version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goapp_users
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - goapp_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp_api
    environment:
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: goapp_users
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - goapp_network
    restart: unless-stopped

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: goapp_test
    environment:
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: goapp_users
      SERVER_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - goapp_network
    command: ["go", "test", "-v", "./..."]

volumes:
  mysql_data:

networks:
  goapp_network:
    driver: bridge
